export default {
    container:{
        flex:1
    },
    header:{
        padding:20,
        flexDirection:'row',
        height:120,
        alignItems:'center',
        backgroundColor:'green',
        justifyContent:'space-between',
    },
    content:{
        flex:4
    },
    footer:{
        height:55,
        flexDirection:'row',
        alignItems:'flex-end'
    },
    headText:{
        fontSize:30,
        color:'white',
        textAlign:'center'
    },
    button:{
        backgroundColor:'green',
        height:55,
        justifyContent:'center',
        alignItems:'center'
    },
    buttonText:{
        color:'white',
        fontSize:20
    }
}